import { Product } from './product.interface';

export const MOCK_PRODUCTS: Product[] = [
    {
        idProducto: 'prd-001',
        nombreProducto: 'Audífonos inalámbricos Studio One',
        descripcion: 'Sonido envolvente, cancelación de ruido y hasta 30 horas de batería.',
        nombreMarca: 'Sonora',
        nombreCategoria: 'Tecnología',
        nombreSubcategoria: 'Audio',
        precio: 189.9,
        precioAnterior: 239.9,
        urlImagen: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 18,
        rating: 4.8,
        reviews: 284,
        badge: 'Más vendido'
    },
    {
        idProducto: 'prd-002',
        nombreProducto: 'Lámpara de mesa Arco',
        descripcion: 'Luz cálida regulable y diseño minimalista para tu espacio favorito.',
        nombreMarca: 'Nórdika',
        nombreCategoria: 'Hogar',
        nombreSubcategoria: 'Iluminación',
        precio: 74.5,
        urlImagen: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 12,
        rating: 4.6,
        reviews: 96,
        badge: 'Diseño destacado'
    },
    {
        idProducto: 'prd-003',
        nombreProducto: 'Mochila urbana Atlas 20 L',
        descripcion: 'Compartimento acolchado para portátil y tejido resistente al agua.',
        nombreMarca: 'Rumbo',
        nombreCategoria: 'Moda',
        nombreSubcategoria: 'Accesorios',
        precio: 92,
        precioAnterior: 115,
        urlImagen: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 9,
        rating: 4.7,
        reviews: 143,
        badge: 'Oferta'
    },
    {
        idProducto: 'prd-004',
        nombreProducto: 'Set de cuidado facial botánico',
        descripcion: 'Rutina esencial con ingredientes de origen vegetal para uso diario.',
        nombreMarca: 'Verde Vivo',
        nombreCategoria: 'Belleza',
        nombreSubcategoria: 'Cuidado de la piel',
        precio: 48.9,
        urlImagen: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 24,
        rating: 4.5,
        reviews: 71
    },
    {
        idProducto: 'prd-005',
        nombreProducto: 'Cafetera compacta Barista',
        descripcion: 'Prepara espresso y café largo con controles sencillos y precisos.',
        nombreMarca: 'Casa Norte',
        nombreCategoria: 'Hogar',
        nombreSubcategoria: 'Cocina',
        precio: 129,
        precioAnterior: 159,
        urlImagen: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 7,
        rating: 4.4,
        reviews: 118,
        badge: 'Precio especial'
    },
    {
        idProducto: 'prd-006',
        nombreProducto: 'Reloj clásico Meridian',
        descripcion: 'Caja de acero, correa intercambiable y resistencia al agua cotidiana.',
        nombreMarca: 'Meridian',
        nombreCategoria: 'Moda',
        nombreSubcategoria: 'Relojes',
        precio: 156,
        urlImagen: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 5,
        rating: 4.9,
        reviews: 203,
        badge: 'Nuevo'
    },
    {
        idProducto: 'prd-007',
        nombreProducto: 'Altavoz portátil Costa',
        descripcion: 'Audio nítido en formato compacto, con conexión Bluetooth estable.',
        nombreMarca: 'Sonora',
        nombreCategoria: 'Tecnología',
        nombreSubcategoria: 'Audio',
        precio: 64.9,
        urlImagen: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 0,
        rating: 4.3,
        reviews: 58
    },
    {
        idProducto: 'prd-008',
        nombreProducto: 'Jarrón de cerámica Ladera',
        descripcion: 'Pieza artesanal de acabado mate, ideal para flores o como acento decorativo.',
        nombreMarca: 'Nórdika',
        nombreCategoria: 'Hogar',
        nombreSubcategoria: 'Decoración',
        precio: 39.5,
        urlImagen: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=900&h=900&q=85',
        stock: 16,
        rating: 4.6,
        reviews: 42
    }
];